# Generated by Django 5.1.3 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_boss_items_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
