# Generated by Django 5.1.3 on 2024-11-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_boss_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
