# Generated by Django 5.1.3 on 2024-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_budget_total_budget_alter_items_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='total_price',
            new_name='total_item',
        ),
        migrations.AddField(
            model_name='budget',
            name='project_name',
            field=models.CharField(default='motor', max_length=64),
            preserve_default=False,
        ),
    ]
