# Generated by Django 5.1.3 on 2024-11-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_budget_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='items',
        ),
        migrations.AddField(
            model_name='items',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='api.budget'),
            preserve_default=False,
        ),
    ]
