# Generated by Django 5.1.3 on 2024-11-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_budget_items_items_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('item', 'budget')},
        ),
    ]
