# Generated by Django 5.1.3 on 2024-11-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_budget_options_alter_items_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created',
            field=models.DateField(auto_created=True, default='2024-11-07'),
            preserve_default=False,
        ),
    ]
