# Generated by Django 5.1.3 on 2024-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_boss_options_alter_materials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
