# Generated by Django 5.1.3 on 2024-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('doc', models.FileField(upload_to='', verbose_name='Curriculum')),
            ],
            options={
                'verbose_name': 'Cv Personal',
                'verbose_name_plural': 'Cvs Personales',
            },
        ),
        migrations.CreateModel(
            name='PersonalImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='personal/', verbose_name='Imagen Personal')),
            ],
            options={
                'verbose_name': 'Imagen Personal',
            },
        ),
    ]
