# Generated by Django 5.1.3 on 2024-11-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tags_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalimagen',
            options={'verbose_name': 'Imagen Personal', 'verbose_name_plural': 'Imagen Personales'},
        ),
    ]
